export const wordsList = [ "sagaz", "negro", "capaz", "vasco", "mexer", "termo",
"senso", "nobre", "algoz", "afeto", "plena", "signo", "pedra", "porte", "beijo",
"vigor", "depor", "audaz", "cifra", "fazer", "sanar", "gabar", "inato", "assim",
"cerne", "casar", "amado", "fosse", "poder", "moral", "torpe", "honra", "muito",
"justo", "feroz", "anexo", "cegar", "enjoo", "etnia", "matar", "sobre", "pavor",
"lapso", "tutor", "sonho", "expor", "haver", "bruto", "casal", "amigo", "pesar",
"tempo", "posse", "laudo", "perto", "bocal", "coser", "genro", "corja", "seara",
"dengo", "prole", "rural", "causa", "dizer", "tenaz", "digno", "dever", "crivo",
"saber", "molde", "vagar", "tchau", "brado", "ceder", "itens", "minar", "renda",
"comum", "atroz", "fossa", "culto", "temor", "sendo", "mundo", "censo", "pauta",
"fugaz", "denso", "cozer", "valha", "odiar", "ainda", "manga", "forte", "clero", 
"vulgo", "estar", "pudor", "regra", "dogma", "louco", "banal", "criar", "jejum",
"impor", "tenro", "desse", "apraz", "berro", "jeito", "ordem", "ileso", "pedir", 
"largo", "viril", "pomar", "cinto", "manso", "canto", "visto", "ontem", "servo",
"prosa", "feliz", "presa", "amiga", "coisa", "fluir", "falar", "cunho", "forma",
"meiga", "vendo", "bolsa", "homem", "pleno", "temer", "visar", "mesmo", "cisma",
"limbo", "magoa", "puder", "acaso", "frota", "vasto", "gerar", "jogar", "afins",
"obter", "valor", "lugar", "linha", "praxe", "crise", "senil", "havia", "misto",
"fluxo", "certo", "enfim", "manto", "fundo", "ritmo", "tomar", "reter", "sigla",
"valia", "grato", "vital", "seiva", "todos", "favor", "vivaz", "abrir", "laico",
"bravo", "prumo", "cerca", "ameno", "sabor", "pardo", "rublo", "falso", "louro",
"olhar", "livro", "levar", "tecer", "burro", "casta", "selar", "fator", "citar",
"rogar", "adiar", "farsa", "arroz", "achar", "coeso", "barro", "redor", "negar",
"legal", "morte", "imune", "sinto", "calvo", "fardo", "exato", "falta", "ativo",
"gente", "carta", "farto", "solar", "ebola", "natal"
]
