export const wordsList = [ "sagaz", "negro", "amago", "exito", "mexer", "termo",
"senso", "nobre", "algoz", "afeto", "plena", "etica", "mutua", "sutil", "tenue",
"vigor", "aquem", "audaz", "porem", "fazer", "sanar", "secao", "inato", "assim",
"cerne", "desde", "ideia", "fosse", "poder", "moral", "torpe", "honra", "muito",
"justo", "feroz", "anexo", "futil", "razao", "etnia", "icone", "sobre", "egide",
"lapso", "mutuo", "sonho", "expor", "haver", "habil", "casal", "amigo", "pesar",
"tempo", "posse", "avido", "entao", "bocal", "coser", "genro", "corja", "seara",
"dengo", "prole", "detem", "causa", "dizer", "tenaz", "digno", "dever", "crivo",
"saber", "obito", "apice", "ansia", "brado", "ceder", "animo", "paria", "graca",
"comum", "atroz", "copia", "culto", "temor", "sendo", "mundo", "censo", "pauta",
"fugaz", "denso", "cozer", "valha", "nenem", "ainda", "vicio", "forte", "reves", 
"vulgo", "estar", "pudor", "regra", "dogma", "louco", "banal", "criar", "pifio",
"impor", "tenro", "desse", "apraz", "reaca", "jeito", "ordem", "atras", "pedir", 
"saude", "viril", "merce", "usura", "manso", "juizo", "sabio", "ontem", "servo",
"prosa", "feliz", "presa", "afago", "coisa", "fluir", "falar", "cunho", "forma",
"meiga", "vendo", "serio", "homem", "pleno", "temer", "visar", "mesmo", "cisma",
"limbo", "magoa", "puder", "acaso", "heroi", "exodo", "gerar", "obvio", "afins",
"obter", "valor", "lugar", "impio", "praxe", "crise", "senil", "havia", "venia",
"fluxo", "certo", "enfim", "alibi", "tedio", "ritmo", "tomar", "reter", "uniao",
"valia", "grato", "vital", "visao", "todos", "favor", "vivaz", "abrir", "laico",
"bravo", "prumo", "facil", "ameno", "genio", "pardo", "rublo", "falso", "possa",
"olhar", "livro", "levar", "tecer", "burro", "casta", "selar", "fator", "citar",
"rogar", "adiar", "farsa", "ranco", "achar", "coeso", "nocao", "epico", "negar",
"legal", "morte", "imune", "sinto", "calvo", "fardo", "exato", "falta", "ativo",
"gente", "carta", "farto", "solar", "ebola", "natal"
]
